spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  data.mongodb:
    host: localhost
    port: 27017
    database : reactTest

---
spring:
  profiles: prod
  data.mongodb:
    host: localhost
    port: 27017
    database : reactTest

---
spring:
  profiles: test